-- ==========================================
-- YESIL PANEL — VERİTABANI GÜNCELLEME SORGULARI
-- ==========================================
-- Bu sorguları Supabase Dashboard -> SQL Editor
-- üzerinden yeni bir sorgu açıp çalıştırın.

-- 1. Abonelerin isim, telefon ve bakiye bilgilerini tutacak tablo
CREATE TABLE IF NOT EXISTS aboneler (
    id bigint primary key generated by default as identity,
    saha_id uuid REFERENCES sahalar(id) ON DELETE CASCADE,
    isim text NOT NULL,
    telefon text,
    bakiye numeric DEFAULT 0 NOT NULL,
    created_at timestamp with time zone default now()
);

-- 2. Mevcut slots tablosuna rezervasyonu yapan kişinin ismini kaydetmek için sütun ekleme
ALTER TABLE slots ADD COLUMN IF NOT EXISTS rezervasyon_isim text;

-- 3. Mevcut abonelikler tablosunu aboneler tablosuna bağlamak için sütun ekleme
ALTER TABLE abonelikler ADD COLUMN IF NOT EXISTS abone_id bigint REFERENCES aboneler(id) ON DELETE SET NULL;

-- 4. RLS (Row Level Security) Ayarları ve Politika Tanımlamaları
ALTER TABLE aboneler ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access" ON aboneler;
CREATE POLICY "Public Access" ON aboneler 
    FOR ALL 
    TO public 
    USING (true) 
    WITH CHECK (true);
